### ISSUE TITLE
Generated doc layout could be improved

### ISSUE THREAD

**Issue by pllim** [aasorg/hacks-collector#13]
Cool project!

Looking at the generated layout, the following could be added/improved:

1. TOC of the hack day on top of the actual hack day page (right after main title).
2. Font size should be distinguished better so the actual hack title stands out. Right now, all the hacks seem to jumble together. The separator lines are not very visible, at least from my Firefox browser on Windows.

**Comment by eteq** [comment]
👍  to all these.  2 is probably basically a layout/css change, but 1 will probably require fiddling around with the generation machinery...  Happy to accept PR's in this direction!

**Comment by pllim** [comment]
For 1, theoretically (by just looking at the codes without actually having experience with Jinga etc), perhaps you can store the titles as a separate YAML structure, and then render them as a list at the top of the `page.html`?

For 2, I think demoting "Creators" from `<h3>` to `<h4>` in `page.html` would be sufficient.

**Comment by eteq** [comment]
Good point - I did 2 just now in 403d81a.

For 1, though, I think having a separate title structure is problematic because then the title has to be in two different places, which will likely confuse anyone who wants to modify something.  And anyway, that would still require reading *that* YAML file and outputting it into the page.

This isn't actually that complicated- it just requires a for loop over the YAML entries, grabbing the title, and then associating those titles with anchors further down the page (e.g. `#hack-0`, `#hack-1`, etc.).  I just haven't had time to do it yet, so if anyone else wants to they are welcome to do so!
